spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: itachiuchihadev3853@gmail.com
    password: whsx qdci ninr bkjn
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            protocols: TLSv1.2
          auth: true
          starttls:
            enable: true